dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: qHIBtD1FJiQvqQO2dy/rb2TeOX1bBZr6kevPz4UnjWLLtaZg1U9eKczaPkbGHptcutycgwaTe421nHGVGJ+2xRMNJyzEnzdmIfihknxD0QoHvdFX6Mqvxs49f5QMNuRxsojPEtNiyl3nuTPXJMvS7SOWDqwbkAA01ruRRu57kvY8FSJucT4auyV9r1JF4FpVuq1/cGJl2dxZx3JKW8OdNI+jkf27P2HlfoDsyr6Jo2c0C00RTjVapmFTfACMPHqFn/RmYzaUpe5kPbeWRNHaHxx+wris+VVdsWsPZ1Ey3sLSx9sWOXtm1MHuUeePtVUR6AisMMeUPYKDZTJHyHgR9dgdC3imvtLc7cntChxdiBqKZVlomaUFEoog+kUtm9TfWDKOQDymaeBDfm8N9prTEtRD3MkFQat+CIa9ywHkipvY7MDCHevfWzDkFplBuixtKpu+wrZ/KYiINVBQ0wlInnX8xgwPxxy5WGfsDGFLTaWPnunGH6xi5fJblngDsLH+wxCkdRWwT1X2Gshba2vM7keH5WwMYLEPB33E9zTHP8DAlWPLBA1K+RY5yTq+qbiybcwI70VJgWtp34vd9DQkd0xBYDSgnvHUr2MJnwi9ef2mxP8tRP/ssLepemK/1C+psex6FbEbFa2JDs2DfvDYyZWSvGgBSXOx/ftmyjuDr94=
