dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: FwJnQqtasZbElrU7G2RtinE4S0neC78tsg4ssPYq3s+Xd3ef8jPkqsgFpDtT3jrJyJwXINSgx+VxkouWRzgw/JJt23OI868CNGknPDTF5mPXciG9jJJwgmcsT4S6WhjL6R6qnDemqOA/yhxCe5uW6lEwMcUG6ZU2Uyxxhf/sLcS9dCx+kE2ajOFmA+COQVumAcXoPUv2IZSr1+IiUnl3DazPoWnJItHd7k51FxTttZ4zNCUDfHbSOtUP29C0cE3BpAXNPhy1NPT6mxGALT5nzDOtmvQBiTQRNQ/DpGIq4RFF6CliANMNxMKyHfw5OlMhqS7Dql8FhOHT3i71fgRsPfdC1TwWzu1IAOga1DgUmqSarX/J8wMcG6sl4JGnsWggJMQLDLK4ipGm5gyyRxHhlyhcQtOkISpBJnFkKB/+KPDU/dP+kzZi5PAyklbupkPH2KXlNPps3eQ3MCUdaamelzrht48STxoJfSRojlU0bqi9yfraA5L7nPjizrwfNUC6zx6pXZ3dqxed/bj3Xqxt8VKGWIH1cHd5Xif+SUdNjSOC9UhQXqbhPcTHVOKdV+0mbzoa860J2oNwlb/pFXcPEm9pjFQ+yN3zyZ2Nc7J6eSgid5fVeT/YvylxrL9yeTTdTW7kwuveeyah8bNbRe+yCgqoXCrSxdZHlBKa+Mqunts=
