version: '3.3'
services:
  post_db:
    env_file:
     - docker.env
    image: mongo:${MONGO_IMAGE_VER}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    env_file:
     - docker.env
    build: ./ui
    image: ${USERNAME}/ui:${UI_IMAGE_VER}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
  post:
    env_file:
     - docker.env
    build: ./post-py
    image: ${USERNAME}/post:${POST_IMAGE_VER}
    networks:
      - front_net
      - back_net
  comment:
    env_file:
     - docker.env
    build: ./comment
    image: ${USERNAME}/comment:${COMM_IMAGE_VER}
    networks:
      - front_net
      - back_net


volumes:
  post_db:

networks:
  front_net:
   ipam:
     config:
      - subnet: 10.0.1.0/24
  back_net:
   ipam:
     config:
      - subnet: 10.0.2.0/24
